// auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';


// modal actions
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SHOW_CART_MODAL = 'SHOW_CART_MODAL';
export const HIDE_CART_MODAL = 'HIDE_CART_MODAL';


// shopping cart actions
export const SET_TOTAL_CART_ITEM = 'SET_TOTAL_CART_ITEM';
export const SET_TOTAL_CART_ITEM_FAIL = 'SET_TOTAL_CART_ITEM_FAIL';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const ADD_CART_ITEM_FAIL = 'ADD_CART_ITEM_FAIL';

// items action
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const GET_ALL_ITEMS_FAIL = 'GET_ALL_ITEMS_FAIL';
export const GET_SINGLE_ITEM = 'GET_SINGLE_ITEM';
export const GET_SINGLE_ITEM_FAIL = 'GET_SINGLE_ITEM_FAIL';
export const GET_ITEMS_BY_DEPARTMENT = 'GET_ITEMS_BY_DEPARTMENT';
export const GET_ITEMS_BY_DEPARTMENT_FAIL = 'GET_ITEMS_BY_DEPARTMENT_FAIL';
export const GET_ITEMS_BY_DEPT_AND_CAT = 'GET_ITEMS_BY_DEPARTMENT_AND_CATEGORY';
export const GET_ITEMS_BY_DEPT_AND_CAT_FAIL = 'GET_ITEMS_BY_DEPARTMENT_AND_CATEGORY_FAIL';
export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const SEARCH_ITEMS_FAIL = 'SEARCH_ITEMS_FAIL';
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';
export const GET_ALL_DEPARTMENTS_FAILS = 'GET_ALL_DEPARTMENTS_FAILS';
export const GET_DEAL_OF_DAY = 'GET_DEAL_OF_DAY';
export const GET_DEAL_OF_DAY_FAIL = 'GET_DEAL_OF_DAY_FAIL';
